Update integration.yml

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -18,34 +18,34 @@ jobs:
         run: flutter pub get
       - name: Check linting
         run: flutter analyze
-  test:
-    needs: lint
-    runs-on: ubuntu-latest
-    steps:
-      - name: Install LCOV
-        run: sudo apt-get install lcov
-      - uses: actions/checkout@v4
-      - uses: subosito/flutter-action@v2
-        with:
-          flutter-version: '3.16.9'
-          channel: 'stable'
-      - name: Download dependencies
-        run: flutter pub get
-      - name: Run tests and collect coverage
-        run: flutter test --coverage
-      - name: Generate coverage report
-        run: lcov --list coverage/lcov.info
-      - name: Verify coverage
-        run: |
-          set -e
-          COVERAGE=$(lcov --summary coverage/lcov.info | grep -Po '(\d+.\d+)%' | head -1)
-          echo "Coverage: $COVERAGE"
-          if [[ $COVERAGE < 1 ]]; then
-            echo "Coverage is below 80%, failing the build"
-            exit 1
-          fi
+  #test:
+    #needs: lint
+    #runs-on: ubuntu-latest
+    #steps:
+      #- name: Install LCOV
+        #run: sudo apt-get install lcov
+      #- uses: actions/checkout@v4
+      #- uses: subosito/flutter-action@v2
+        #with:
+          #flutter-version: '3.16.9'
+          #channel: 'stable'
+      #- name: Download dependencies
+        #run: flutter pub get
+      #- name: Run tests and collect coverage
+        #run: flutter test --coverage
+      #- name: Generate coverage report
+        #run: lcov --list coverage/lcov.info
+      #- name: Verify coverage
+        #run: |
+          #set -e
+          #COVERAGE=$(lcov --summary coverage/lcov.info | grep -Po '(\d+.\d+)%' | head -1)
+          #echo "Coverage: $COVERAGE"
+          #if [[ $COVERAGE < 1 ]]; then
+            #echo "Coverage is below 80%, failing the build"
+            #exit 1
+          #fi
   build:
-    needs: test
+    #needs: test
     runs-on: ubuntu-latest
     steps:
       - name: Set up JDK 17
